### ISSUE TITLE
many Switcheo trades are missing from the list of returned trades

### ISSUE THREAD

**Issue by Eporediese** [benammann/switcheo-exporter#44]
To reproduce:

1) Navigate to https://benammann.github.io/switcheo-exporter/#/address/AG5taCpDjaea9qqZVHf6aXXAamGJRRufgh

2) Compare the list of the returned transactions in the trade history with those returned from 
https://neotracker.io/address/AG5taCpDjaea9qqZVHf6aXXAamGJRRufgh

You will see that in the exporter list there are large date ranges where there are no trades returned, for example between 5/13 and 7/16. Then there is another large gap until mid-November. In these periods many trades were successfully executed on Switcheo from this public address.

Otherwise promising tool. Indispensable for Switcheo users during US tax season!

[exported_list.txt](https://github.com/benammann/switcheo-exporter/files/2801053/exported_list.txt)

**Comment by benammann** [comment]
Hi @Eporediese ,

thanks for opening this issue.

I'm going to compare the exported trades with the trades served by the api tomorrow.

This will be fixed very soon :)

cheers

**Comment by benammann** [comment]
I think the order is going to be removed by this lines of code https://github.com/benammann/switcheo-exporter/blob/e87e355e38a0eda428f2281184414a94f1b86972/src/helpers/convertOrders.js#L35

going to fix this tomorrow

**Comment by Eporediese** [comment]
Thanks Ben. I look forward to trying the new version.
   On Monday, January 28, 2019, 5:08:37 PM EST, Ben Ammann <notifications@github.com> wrote: 
 
 
I think the order is going to be removed by this lines of code https://github.com/benammann/switcheo-exporter/blob/e87e355e38a0eda428f2281184414a94f1b86972/src/helpers/convertOrders.js#L35

going to fix this tomorrow

**Comment by benammann** [comment]
So i double checked the getting converted by my script and the orders served by the official switcheo api. As i can see there are no differences.

I'm gonna close this issue for now. Feel free to reopen it.

**Comment by benammann** [comment]
I'll have a look on it, thank you!

> BTW I was thinking that once this is all figured out, you might consider adding an option to format the CSV file output so that it is compatible with bitcoin.tax CSV input.  Regards, Duncan.

**Comment by RavenXce** [comment]
Based on a quick look it seems that the `/v2/orders` endpoint is being used for this. The default number of orders fetched is 50, and can be configured to a maximum of 200 using the `limit` param. (See: https://docs.switcheo.network/#get-orders)

I think https://github.com/benammann/switcheo-exporter/blob/master/src/actions/address/orders/fetchOrders.js#L82 needs to be changed to a loop where orders are fetched in batches using the previous batch's last order id set as the `before_id` param, until there is nothing left to fetch.

**Comment by benammann** [comment]
@RavenXce Thanks for the reply. That explains the gaps. Going to fix it soon :)

**Comment by Eporediese** [comment]
The returned list looks correct now. Thanks @benamman and @RavenXce.
